#!/usr/bin/env bash
#
# Installation (OS X):
#
# - save this file as "gpti" somewhere in your path
# - get an openai api key at: https://platform.openai.com/account/api-keys
# - save the openai api key to your keychain with:
#     security add-generic-password -s 'openai' -a '<account name>' -w '<api key>'
# - If you don't already have `jq`, install it with `brew install jq` or whatever
# - optional, if using iterm2: install `imgcat` somewhere in your path:
#     - https://iterm2.com/utilities/imgcat
#
# If you prefer, you can put your API key directly in here or modify the 
# `OPENAIKEY` line to use your preferred secrets manager

OPENAIKEY=$(security find-generic-password -w -s 'openai')
SIZE="1024x1024"
VERBOSE=
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/gpt-bash"
DB="${DATA_DIR}/openai.sqlite3"

function usage {
    cat <<"EOF"
gpti [-vh] <description>

generates an image via openai's /images/generations endpoint

FLAGS: 

    -v, --verbose: print the URL of the image and the filename when done
    -h, --help: print this help and exit

EXAMPLE USAGE:

    gpti a drone photo of fenway park on opening day

STORAGE:

    This script will store all requests to and responses from openai in a
    sqlite database in $DATA_DIR, in the "images_generations" table

NOTE:

    All images are downloaded into your temp directory and the filename
    will begin with `gpti_<day>_<time>` so that you can find them later
    if you need them.
EOF
exit 1
}

function gptirequest {
    cat <<EOF
{
  "prompt": "$@",
  "n": 1,
  "size": "$SIZE"
}
EOF
}

function gpti {
    dt=$(date +"%Y%m%d_%H%M")
    f="$(mktemp -t "gpti_$dt").png"
    request=$(gptirequest "$@")
    if res=$(curl https://api.openai.com/v1/images/generations -s \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $OPENAIKEY" \
        -d "$request"); then

        # insert the request and response into the database. The funny-looking
        # search and replaces turn single quotes (') into doubled single quotes
        # (''), which is how sqlite wants you to escape them. It _seems_ that
        # the only thing we need to escape are single quotes, but maybe this is
        # an injection vector Iunno. Strings in bash, amirite?
        sqlite3 "$DB" <<EOF
INSERT INTO images_generations VALUES(
    '${request//"'"/"''"}',
    '${res//"'"/"''"}');
EOF

        # if there's an "error" key in the return value, we didn't succeed.
        # Print and quit
        if echo "$res" | jq -e 'has("error")' &> /dev/null ; then
            echo "error: $res"
            exit 1
        fi
        url=$(echo "$res" | jq -r '.data[0].url')
    else
        sqlite3 "$DB" <<EOF
INSERT INTO images_generations VALUES( '${request//"'"/"''"}', '');
EOF
        tput setaf 1
        echo "error: $res"
        tput sgr0
        exit 1
    fi

    # download the image to a tempfile, and print it to the terminal
    curl -s "$url" -o "$f"

    # if imgcat is present, try outputting the image to the terminal
    if which imgcat &> /dev/null ; then
        echo
        imgcat < "$f"
    fi

    if [[ -n $VERBOSE ]]; then
        echo "URL: $url"
        echo "file: $f"
    fi
}

case $1 in
    help | -h | --help)
        usage
        ;;
    -v | --verbose)
        VERBOSE=true
        shift
        ;;
    -vv | --very-verbose)
        set -x
        shift
        ;;
esac

if [[ -z $OPENAIKEY ]]; then
    tput setaf 1
    printf "ERROR: unable to find an openAI API key.\n\n"
    tput sgr0
    printf "You can set one by editing this script directly or, if you're on a mac, using:\n\n    security add-generic-password -s 'openai' -a '<account name>' -w '<api key>'\n\n"
    exit 1
fi

# if the directory for storing our database (~/.local/share/gpt-bash/ by
# default) doesn't exist, create it
if [ ! -d "$DATA_DIR" ]; then
    mkdir -p "$DATA_DIR"
fi

# if our table doesn't exist, create a table to use. I'm YOLOing versioning
# here
sqlite3 "$DB" <<EOF
CREATE TABLE IF NOT EXISTS images_generations(
    query text,   -- the JSON query sent to openai
    response text -- the JSON response received from openai
);
EOF

gpti "$@"
